### ISSUE TITLE
Freeze and Ice Shards

### ISSUE THREAD

**Issue by GoodToast1** [ZS-NVB/CoreModCollection#5]
For some reason freeze is only freezing for ~2 seconds even though duration says 8-13s. Also ice shards is having no affect on monsters.

Also I second the idea of uncapped battle traits, would be cool to experiment with!

**Comment by GoodToast1** [comment]
Ice shards is working now

**Comment by ZS-NVB** [comment]
Not a bug, you had the one which adds diminishing returns the more something is frozen on (not worth using if not uncapping skills) and the one which makes ice shards do less the more it's cast on a target to stop enraging giants only from being worth it and a side effect of that is that ice shards reduces both health and max health and it ends up looking like it's not doing anything.
